### ISSUE TITLE
OdometryPublisherでSegmentation Faultが発生する

### ISSUE THREAD

**Issue by 98shimpei** [Naoki-Hiraoka/choreonoid_ros_ext_plugin#1]
このパッケージを使ってL515とT265のシミュレーションを試しているのですが、OdometryPublisherでsegmentation faultを起こしてしまいました。
OdometryPublisherItem.cppの79行目付近が原因のようなのですが、
`if(this->frameId_.size()!=0) odom.child_frame_id = this->childFrameId_;`
の部分は
`if(this->childFrameId_.size()!=0) odom.child_frame_id = this->childFrameId_;`
と変更すると想定と異なるのでしょうか。

**Comment by Naoki-Hiraoka** [comment]
ありがとうございます．その通りです．
